### ISSUE TITLE
Not even working.

### ISSUE THREAD

**Issue by imhandmade** [JavaFactoryDev/XCore-Wiki#1]
"When i am put xcore to the plugins foled it s just not working. I am using only spigot (not a bungeecord). Why it s happend, whot i am do wrong? Is it only bungeecord plugin?" - **another person on the spigot page.**

I think so, because I'm getting the " http://prntscr.com/osebhb "
Even with bungee set to false, nothing ever gets setup. Also latest update still says "v.1.0" when it's really 1.1.2
Installation seems to be bugging out if you are not using it for bungee, but I have yet to even try that either.

**To Reproduce**
litterly just drag and drop into plugins, thats it.

**Expected behavior**
actually work

**Screenshots**
provided above.

**Desktop (please complete the following information):**
Has nothing to do with this.

**Smartphone (please complete the following information):**
Nothing to do with this.

**Additional context**
Not sure why people are giving 5 star reviews on a plugin that doesn't even enable on a regular server. They are your friends I guess? I'm not trying to be an ass or anything of the sort, but you should probably actually check the plugin's discussion page every once in a while.

**Comment by JavaFactoryDev** [comment]
Sorry for the late response somehow I'm not getting any king of notification when an issue is created.

I'm sorry for the inconvenience, XCore is currently not supporting only spigot servers. As I've seen that there were several requests doing this, this will be added soon.
No, the people who gave the reviews are not my friends, they just use BungeeCord & Spigot. As described in the wiki, the idea is to join the server after the first installation, so that the plugin can adjust itself. The first time data will be exchanged between Proxy & Spigot, so that's no problem afterward.

However, some functions will not work on SpigotOnly servers.

Greetings,
Leonhard | JavaFactory | EsGibtKeineMitte
